name: Meter Emulator
description: >-
  Energy meter emulator with pluggable frontends and backends.
  Emulates a Shelly Pro 3EM using Enphase Envoy data, enabling
  devices like the Marstek Venus-E to work with Enphase systems.
version: "0.1.5"
slug: meter-emulator
url: https://github.com/CoRfr/meter-emulator
image: ghcr.io/corfr/meter-emulator
arch:
  - amd64
  - aarch64
host_network: true
options:
  frontend_type: shelly
  shelly_phases: "1"
  shelly_mdns: true
  backend_type: envoy
  envoy_host: ""
  envoy_token: ""
  envoy_poll_interval: 2.0
  envoy_verify_ssl: false
  envoy_username: ""
  envoy_password: ""
  envoy_serial: ""
schema:
  frontend_type: "list(shelly)"
  shelly_mac: "str?"
  shelly_phases: "list(1|3)"
  shelly_mdns: bool
  backend_type: "list(envoy)"
  envoy_host: str
  envoy_token: "password?"
  envoy_poll_interval: float
  envoy_verify_ssl: bool
  envoy_username: "str?"
  envoy_password: "password?"
  envoy_serial: "str?"
